#!/bin/bash
set -e

# Get rid of existing binary
rm -f wundertools

go generate

BUILDTIME=$(date --rfc-3339 ns | sed -e 's/ /T/') &> /dev/null
GITCOMMIT=$(git rev-parse --short HEAD)

# Build binaries
go build \
   -ldflags="-w -X github.com/james-nesbitt/wundertools-go/version.GITCOMMIT=${GITCOMMIT} -X github.com/james-nesbitt/wundertools-go/version.BUILDTIME=${BUILDTIME} -X github.com/james-nesbitt/wundertools/version.SHOWWARNING=${SHOWWARNING}" \
   -o bundles/wundertools \
   ./cli/main
